from actions import Actions

# ONLY USES STAND, HIT, DOUBLE, SPLIT

# Split aces only get 1 card

# SURRENDER is not implemented yet

# Basic strategy when dealer stands on a soft 17
# (player_hand_value, dealer_upcard)
def get_basic_strategy():
    return {
        'hard': {
            ('4', '2'): Actions.HIT.name,
            ('4', '3'): Actions.HIT.name,
            ('4', '4'): Actions.HIT.name,
            ('4', '5'): Actions.HIT.name,
            ('4', '6'): Actions.HIT.name,
            ('4', '7'): Actions.HIT.name,
            ('4', '8'): Actions.HIT.name,
            ('4', '9'): Actions.HIT.name,
            ('4', '10'): Actions.HIT.name,
            ('4', 'J'): Actions.HIT.name,
            ('4', 'Q'): Actions.HIT.name,
            ('4', 'K'): Actions.HIT.name,
            ('4', 'A'): Actions.HIT.name,

            ('5', '2'): Actions.HIT.name,
            ('5', '3'): Actions.HIT.name,
            ('5', '4'): Actions.HIT.name,
            ('5', '5'): Actions.HIT.name,
            ('5', '6'): Actions.HIT.name,
            ('5', '7'): Actions.HIT.name,
            ('5', '8'): Actions.HIT.name,
            ('5', '9'): Actions.HIT.name,
            ('5', '10'): Actions.HIT.name,
            ('5', 'J'): Actions.HIT.name,
            ('5', 'Q'): Actions.HIT.name,
            ('5', 'K'): Actions.HIT.name,
            ('5', 'A'): Actions.HIT.name,

            ('6', '2'): Actions.HIT.name,
            ('6', '3'): Actions.HIT.name,
            ('6', '4'): Actions.HIT.name,
            ('6', '5'): Actions.HIT.name,
            ('6', '6'): Actions.HIT.name,
            ('6', '7'): Actions.HIT.name,
            ('6', '8'): Actions.HIT.name,
            ('6', '9'): Actions.HIT.name,
            ('6', '10'): Actions.HIT.name,
            ('6', 'J'): Actions.HIT.name,
            ('6', 'Q'): Actions.HIT.name,
            ('6', 'K'): Actions.HIT.name,
            ('6', 'A'): Actions.HIT.name,

            ('7', '2'): Actions.HIT.name,
            ('7', '3'): Actions.HIT.name,
            ('7', '4'): Actions.HIT.name,
            ('7', '5'): Actions.HIT.name,
            ('7', '6'): Actions.HIT.name,
            ('7', '7'): Actions.HIT.name,
            ('7', '8'): Actions.HIT.name,
            ('7', '9'): Actions.HIT.name,
            ('7', '10'): Actions.HIT.name,
            ('7', 'J'): Actions.HIT.name,
            ('7', 'Q'): Actions.HIT.name,
            ('7', 'K'): Actions.HIT.name,
            ('7', 'A'): Actions.HIT.name,

            ('8', '2'): Actions.HIT.name,
            ('8', '3'): Actions.HIT.name,
            ('8', '4'): Actions.HIT.name,
            ('8', '5'): Actions.HIT.name,
            ('8', '6'): Actions.HIT.name,
            ('8', '7'): Actions.HIT.name,
            ('8', '8'): Actions.HIT.name,
            ('8', '9'): Actions.HIT.name,
            ('8', '10'): Actions.HIT.name,
            ('8', 'J'): Actions.HIT.name,
            ('8', 'Q'): Actions.HIT.name,
            ('8', 'K'): Actions.HIT.name,
            ('8', 'A'): Actions.HIT.name,

            ('9', '2'): Actions.HIT.name,
            ('9', '3'): Actions.DOUBLE.name,
            ('9', '4'): Actions.DOUBLE.name,
            ('9', '5'): Actions.DOUBLE.name,
            ('9', '6'): Actions.DOUBLE.name,
            ('9', '7'): Actions.HIT.name,
            ('9', '8'): Actions.HIT.name,
            ('9', '9'): Actions.HIT.name,
            ('9', '10'): Actions.HIT.name,
            ('9', 'J'): Actions.HIT.name,
            ('9', 'Q'): Actions.HIT.name,
            ('9', 'K'): Actions.HIT.name,
            ('9', 'A'): Actions.HIT.name,

            ('10', '2'): Actions.DOUBLE.name,
            ('10', '3'): Actions.DOUBLE.name,
            ('10', '4'): Actions.DOUBLE.name,
            ('10', '5'): Actions.DOUBLE.name,
            ('10', '6'): Actions.DOUBLE.name,
            ('10', '7'): Actions.DOUBLE.name,
            ('10', '8'): Actions.DOUBLE.name,
            ('10', '9'): Actions.DOUBLE.name,
            ('10', '10'): Actions.HIT.name,
            ('10', 'J'): Actions.HIT.name,
            ('10', 'Q'): Actions.HIT.name,
            ('10', 'K'): Actions.HIT.name,
            ('10', 'A'): Actions.HIT.name,

            ('11', '2'): Actions.DOUBLE.name,
            ('11', '3'): Actions.DOUBLE.name,
            ('11', '4'): Actions.DOUBLE.name,
            ('11', '5'): Actions.DOUBLE.name,
            ('11', '6'): Actions.DOUBLE.name,
            ('11', '7'): Actions.DOUBLE.name,
            ('11', '8'): Actions.DOUBLE.name,
            ('11', '9'): Actions.DOUBLE.name,
            ('11', '10'): Actions.DOUBLE.name,
            ('11', 'J'): Actions.DOUBLE.name,
            ('11', 'Q'): Actions.DOUBLE.name,
            ('11', 'K'): Actions.DOUBLE.name,
            ('11', 'A'): Actions.HIT.name,

            ('12', '2'): Actions.HIT.name,
            ('12', '3'): Actions.HIT.name,
            ('12', '4'): Actions.STAND.name,
            ('12', '5'): Actions.STAND.name,
            ('12', '6'): Actions.STAND.name,
            ('12', '7'): Actions.HIT.name,
            ('12', '8'): Actions.HIT.name,
            ('12', '9'): Actions.HIT.name,
            ('12', '10'): Actions.HIT.name,
            ('12', 'J'): Actions.HIT.name,
            ('12', 'Q'): Actions.HIT.name,
            ('12', 'K'): Actions.HIT.name,
            ('12', 'A'): Actions.HIT.name,

            ('13', '2'): Actions.STAND.name,
            ('13', '3'): Actions.STAND.name,
            ('13', '4'): Actions.STAND.name,
            ('13', '5'): Actions.STAND.name,
            ('13', '6'): Actions.STAND.name,
            ('13', '7'): Actions.HIT.name,
            ('13', '8'): Actions.HIT.name,
            ('13', '9'): Actions.HIT.name,
            ('13', '10'): Actions.HIT.name,
            ('13', 'J'): Actions.HIT.name,
            ('13', 'Q'): Actions.HIT.name,
            ('13', 'K'): Actions.HIT.name,
            ('13', 'A'): Actions.HIT.name,

            ('14', '2'): Actions.STAND.name,
            ('14', '3'): Actions.STAND.name,
            ('14', '4'): Actions.STAND.name,
            ('14', '5'): Actions.STAND.name,
            ('14', '6'): Actions.STAND.name,
            ('14', '7'): Actions.HIT.name,
            ('14', '8'): Actions.HIT.name,
            ('14', '9'): Actions.HIT.name,
            ('14', '10'): Actions.HIT.name,
            ('14', 'J'): Actions.HIT.name,
            ('14', 'Q'): Actions.HIT.name,
            ('14', 'K'): Actions.HIT.name,
            ('14', 'A'): Actions.HIT.name,

            ('15', '2'): Actions.STAND.name,
            ('15', '3'): Actions.STAND.name,
            ('15', '4'): Actions.STAND.name,
            ('15', '5'): Actions.STAND.name,
            ('15', '6'): Actions.STAND.name,
            ('15', '7'): Actions.HIT.name,
            ('15', '8'): Actions.HIT.name,
            ('15', '9'): Actions.HIT.name,
            ('15', '10'): Actions.HIT.name,
            ('15', 'J'): Actions.HIT.name,
            ('15', 'Q'): Actions.HIT.name,
            ('15', 'K'): Actions.HIT.name,
            ('15', 'A'): Actions.HIT.name,

            ('16', '2'): Actions.STAND.name,
            ('16', '3'): Actions.STAND.name,
            ('16', '4'): Actions.STAND.name,
            ('16', '5'): Actions.STAND.name,
            ('16', '6'): Actions.STAND.name,
            ('16', '7'): Actions.HIT.name,
            ('16', '8'): Actions.HIT.name,
            ('16', '9'): Actions.HIT.name,
            ('16', '10'): Actions.HIT.name,
            ('16', 'J'): Actions.HIT.name,
            ('16', 'Q'): Actions.HIT.name,
            ('16', 'K'): Actions.HIT.name,
            ('16', 'A'): Actions.HIT.name,

            ('17', '2'): Actions.STAND.name,
            ('17', '3'): Actions.STAND.name,
            ('17', '4'): Actions.STAND.name,
            ('17', '5'): Actions.STAND.name,
            ('17', '6'): Actions.STAND.name,
            ('17', '7'): Actions.STAND.name,
            ('17', '8'): Actions.STAND.name,
            ('17', '9'): Actions.STAND.name,
            ('17', '10'): Actions.STAND.name,
            ('17', 'J'): Actions.STAND.name,
            ('17', 'Q'): Actions.STAND.name,
            ('17', 'K'): Actions.STAND.name,
            ('17', 'A'): Actions.STAND.name,

            ('18', '2'): Actions.STAND.name,
            ('18', '3'): Actions.STAND.name,
            ('18', '4'): Actions.STAND.name,
            ('18', '5'): Actions.STAND.name,
            ('18', '6'): Actions.STAND.name,
            ('18', '7'): Actions.STAND.name,
            ('18', '8'): Actions.STAND.name,
            ('18', '9'): Actions.STAND.name,
            ('18', '10'): Actions.STAND.name,
            ('18', 'J'): Actions.STAND.name,
            ('18', 'Q'): Actions.STAND.name,
            ('18', 'K'): Actions.STAND.name,
            ('18', 'A'): Actions.STAND.name,

            ('19', '2'): Actions.STAND.name,
            ('19', '3'): Actions.STAND.name,
            ('19', '4'): Actions.STAND.name,
            ('19', '5'): Actions.STAND.name,
            ('19', '6'): Actions.STAND.name,
            ('19', '7'): Actions.STAND.name,
            ('19', '8'): Actions.STAND.name,
            ('19', '9'): Actions.STAND.name,
            ('19', '10'): Actions.STAND.name,
            ('19', 'J'): Actions.STAND.name,
            ('19', 'Q'): Actions.STAND.name,
            ('19', 'K'): Actions.STAND.name,
            ('19', 'A'): Actions.STAND.name,

            ('20', '2'): Actions.STAND.name,
            ('20', '3'): Actions.STAND.name,
            ('20', '4'): Actions.STAND.name,
            ('20', '5'): Actions.STAND.name,
            ('20', '6'): Actions.STAND.name,
            ('20', '7'): Actions.STAND.name,
            ('20', '8'): Actions.STAND.name,
            ('20', '9'): Actions.STAND.name,
            ('20', '10'): Actions.STAND.name,
            ('20', 'J'): Actions.STAND.name,
            ('20', 'Q'): Actions.STAND.name,
            ('20', 'K'): Actions.STAND.name,
            ('20', 'A'): Actions.STAND.name,

            ('21', '2'): Actions.STAND.name,
            ('21', '3'): Actions.STAND.name,
            ('21', '4'): Actions.STAND.name,
            ('21', '5'): Actions.STAND.name,
            ('21', '6'): Actions.STAND.name,
            ('21', '7'): Actions.STAND.name,
            ('21', '8'): Actions.STAND.name,
            ('21', '9'): Actions.STAND.name,
            ('21', '10'): Actions.STAND.name,
            ('21', 'J'): Actions.STAND.name,
            ('21', 'Q'): Actions.STAND.name,
            ('21', 'K'): Actions.STAND.name,
            ('21', 'A'): Actions.STAND.name,
        },

        'soft': {

            ('12', '2'): Actions.HIT.name,
            ('12', '3'): Actions.HIT.name,
            ('12', '4'): Actions.HIT.name,
            ('12', '5'): Actions.HIT.name,
            ('12', '6'): Actions.HIT.name,
            ('12', '7'): Actions.HIT.name,
            ('12', '8'): Actions.HIT.name,
            ('12', '9'): Actions.HIT.name,
            ('12', '10'): Actions.HIT.name,
            ('12', 'J'): Actions.HIT.name,
            ('12', 'Q'): Actions.HIT.name,
            ('12', 'K'): Actions.HIT.name,
            ('12', 'A'): Actions.HIT.name,

            ('13', '2'): Actions.HIT.name,
            ('13', '3'): Actions.HIT.name,
            ('13', '4'): Actions.HIT.name,
            ('13', '5'): Actions.DOUBLE.name,
            ('13', '6'): Actions.DOUBLE.name,
            ('13', '7'): Actions.HIT.name,
            ('13', '8'): Actions.HIT.name,
            ('13', '9'): Actions.HIT.name,
            ('13', '10'): Actions.HIT.name,
            ('13', 'J'): Actions.HIT.name,
            ('13', 'Q'): Actions.HIT.name,
            ('13', 'K'): Actions.HIT.name,
            ('13', 'A'): Actions.HIT.name,

            ('14', '2'): Actions.HIT.name,
            ('14', '3'): Actions.HIT.name,
            ('14', '4'): Actions.HIT.name,
            ('14', '5'): Actions.DOUBLE.name,
            ('14', '6'): Actions.DOUBLE.name,
            ('14', '7'): Actions.HIT.name,
            ('14', '8'): Actions.HIT.name,
            ('14', '9'): Actions.HIT.name,
            ('14', '10'): Actions.HIT.name,
            ('14', 'J'): Actions.HIT.name,
            ('14', 'Q'): Actions.HIT.name,
            ('14', 'K'): Actions.HIT.name,
            ('14', 'A'): Actions.HIT.name,

            ('15', '2'): Actions.HIT.name,
            ('15', '3'): Actions.HIT.name,
            ('15', '4'): Actions.DOUBLE.name,
            ('15', '5'): Actions.DOUBLE.name,
            ('15', '6'): Actions.DOUBLE.name,
            ('15', '7'): Actions.HIT.name,
            ('15', '8'): Actions.HIT.name,
            ('15', '9'): Actions.HIT.name,
            ('15', '10'): Actions.HIT.name,
            ('15', 'J'): Actions.HIT.name,
            ('15', 'Q'): Actions.HIT.name,
            ('15', 'K'): Actions.HIT.name,
            ('15', 'A'): Actions.HIT.name,

            ('16', '2'): Actions.HIT.name,
            ('16', '3'): Actions.HIT.name,
            ('16', '4'): Actions.DOUBLE.name,
            ('16', '5'): Actions.DOUBLE.name,
            ('16', '6'): Actions.DOUBLE.name,
            ('16', '7'): Actions.HIT.name,
            ('16', '8'): Actions.HIT.name,
            ('16', '9'): Actions.HIT.name,
            ('16', '10'): Actions.HIT.name,
            ('16', 'J'): Actions.HIT.name,
            ('16', 'Q'): Actions.HIT.name,
            ('16', 'K'): Actions.HIT.name,
            ('16', 'A'): Actions.HIT.name,

            ('17', '2'): Actions.HIT.name,
            ('17', '3'): Actions.DOUBLE.name,
            ('17', '4'): Actions.DOUBLE.name,
            ('17', '5'): Actions.DOUBLE.name,
            ('17', '6'): Actions.DOUBLE.name,
            ('17', '7'): Actions.HIT.name,
            ('17', '8'): Actions.HIT.name,
            ('17', '9'): Actions.HIT.name,
            ('17', '10'): Actions.HIT.name,
            ('17', 'J'): Actions.HIT.name,
            ('17', 'Q'): Actions.HIT.name,
            ('17', 'K'): Actions.HIT.name,
            ('17', 'A'): Actions.HIT.name,

            ('18', '2'): Actions.STAND.name,
            ('18', '3'): Actions.DOUBLE.name,
            ('18', '4'): Actions.DOUBLE.name,
            ('18', '5'): Actions.DOUBLE.name,
            ('18', '6'): Actions.DOUBLE.name,
            ('18', '7'): Actions.STAND.name,
            ('18', '8'): Actions.STAND.name,
            ('18', '9'): Actions.HIT.name,
            ('18', '10'): Actions.HIT.name,
            ('18', 'J'): Actions.HIT.name,
            ('18', 'Q'): Actions.HIT.name,
            ('18', 'K'): Actions.HIT.name,
            ('18', 'A'): Actions.HIT.name,

            ('19', '2'): Actions.STAND.name,
            ('19', '3'): Actions.STAND.name,
            ('19', '4'): Actions.STAND.name,
            ('19', '5'): Actions.STAND.name,
            ('19', '6'): Actions.STAND.name,
            ('19', '7'): Actions.STAND.name,
            ('19', '8'): Actions.STAND.name,
            ('19', '9'): Actions.STAND.name,
            ('19', '10'): Actions.STAND.name,
            ('19', 'J'): Actions.STAND.name,
            ('19', 'Q'): Actions.STAND.name,
            ('19', 'K'): Actions.STAND.name,
            ('19', 'A'): Actions.STAND.name,

            ('20', '2'): Actions.STAND.name,
            ('20', '3'): Actions.STAND.name,
            ('20', '4'): Actions.STAND.name,
            ('20', '5'): Actions.STAND.name,
            ('20', '6'): Actions.STAND.name,
            ('20', '7'): Actions.STAND.name,
            ('20', '8'): Actions.STAND.name,
            ('20', '9'): Actions.STAND.name,
            ('20', '10'): Actions.STAND.name,
            ('20', 'J'): Actions.STAND.name,
            ('20', 'Q'): Actions.STAND.name,
            ('20', 'K'): Actions.STAND.name,
            ('20', 'A'): Actions.STAND.name,

            ('21', '2'): Actions.STAND.name,
            ('21', '3'): Actions.STAND.name,
            ('21', '4'): Actions.STAND.name,
            ('21', '5'): Actions.STAND.name,
            ('21', '6'): Actions.STAND.name,
            ('21', '7'): Actions.STAND.name,
            ('21', '8'): Actions.STAND.name,
            ('21', '9'): Actions.STAND.name,
            ('21', '10'): Actions.STAND.name,
            ('21', 'J'): Actions.STAND.name,
            ('21', 'Q'): Actions.STAND.name,
            ('21', 'K'): Actions.STAND.name,
            ('21', 'A'): Actions.STAND.name,

        },

        'pair': {
            ('2', '2'): Actions.HIT.name,
            ('2', '3'): Actions.HIT.name,
            ('2', '4'): Actions.SPLIT.name,
            ('2', '5'): Actions.SPLIT.name,
            ('2', '6'): Actions.SPLIT.name,
            ('2', '7'): Actions.SPLIT.name,
            ('2', '8'): Actions.HIT.name,
            ('2', '9'): Actions.HIT.name,
            ('2', '10'): Actions.HIT.name,
            ('2', 'J'): Actions.HIT.name,
            ('2', 'Q'): Actions.HIT.name,
            ('2', 'K'): Actions.HIT.name,
            ('2', 'A'): Actions.HIT.name,

            ('3', '2'): Actions.HIT.name,
            ('3', '3'): Actions.HIT.name,
            ('3', '4'): Actions.SPLIT.name,
            ('3', '5'): Actions.SPLIT.name,
            ('3', '6'): Actions.SPLIT.name,
            ('3', '7'): Actions.SPLIT.name,
            ('3', '8'): Actions.HIT.name,
            ('3', '9'): Actions.HIT.name,
            ('3', '10'): Actions.HIT.name,
            ('3', 'J'): Actions.HIT.name,
            ('3', 'Q'): Actions.HIT.name,
            ('3', 'K'): Actions.HIT.name,
            ('3', 'A'): Actions.HIT.name,

            ('4', '2'): Actions.HIT.name,
            ('4', '3'): Actions.HIT.name,
            ('4', '4'): Actions.HIT.name,
            ('4', '5'): Actions.HIT.name,
            ('4', '6'): Actions.HIT.name,
            ('4', '7'): Actions.HIT.name,
            ('4', '8'): Actions.HIT.name,
            ('4', '9'): Actions.HIT.name,
            ('4', '10'): Actions.HIT.name,
            ('4', 'J'): Actions.HIT.name,
            ('4', 'Q'): Actions.HIT.name,
            ('4', 'K'): Actions.HIT.name,
            ('4', 'A'): Actions.HIT.name,

            ('5', '2'): Actions.DOUBLE.name,
            ('5', '3'): Actions.DOUBLE.name,
            ('5', '4'): Actions.DOUBLE.name,
            ('5', '5'): Actions.DOUBLE.name,
            ('5', '6'): Actions.DOUBLE.name,
            ('5', '7'): Actions.DOUBLE.name,
            ('5', '8'): Actions.DOUBLE.name,
            ('5', '9'): Actions.DOUBLE.name,
            ('5', '10'): Actions.HIT.name,
            ('5', 'J'): Actions.HIT.name,
            ('5', 'Q'): Actions.HIT.name,
            ('5', 'K'): Actions.HIT.name,
            ('5', 'A'): Actions.HIT.name,

            ('6', '2'): Actions.HIT.name,
            ('6', '3'): Actions.SPLIT.name,
            ('6', '4'): Actions.SPLIT.name,
            ('6', '5'): Actions.SPLIT.name,
            ('6', '6'): Actions.SPLIT.name,
            ('6', '7'): Actions.HIT.name,
            ('6', '8'): Actions.HIT.name,
            ('6', '9'): Actions.HIT.name,
            ('6', '10'): Actions.HIT.name,
            ('6', 'J'): Actions.HIT.name,
            ('6', 'Q'): Actions.HIT.name,
            ('6', 'K'): Actions.HIT.name,
            ('6', 'A'): Actions.HIT.name,

            ('7', '2'): Actions.SPLIT.name,
            ('7', '3'): Actions.SPLIT.name,
            ('7', '4'): Actions.SPLIT.name,
            ('7', '5'): Actions.SPLIT.name,
            ('7', '6'): Actions.SPLIT.name,
            ('7', '7'): Actions.SPLIT.name,
            ('7', '8'): Actions.HIT.name,
            ('7', '9'): Actions.HIT.name,
            ('7', '10'): Actions.HIT.name,
            ('7', 'J'): Actions.HIT.name,
            ('7', 'Q'): Actions.HIT.name,
            ('7', 'K'): Actions.HIT.name,
            ('7', 'A'): Actions.HIT.name,

            ('8', '2'): Actions.SPLIT.name,
            ('8', '3'): Actions.SPLIT.name,
            ('8', '4'): Actions.SPLIT.name,
            ('8', '5'): Actions.SPLIT.name,
            ('8', '6'): Actions.SPLIT.name,
            ('8', '7'): Actions.SPLIT.name,
            ('8', '8'): Actions.SPLIT.name,
            ('8', '9'): Actions.SPLIT.name,
            ('8', '10'): Actions.SPLIT.name,
            ('8', 'J'): Actions.SPLIT.name,
            ('8', 'Q'): Actions.SPLIT.name,
            ('8', 'K'): Actions.SPLIT.name,
            ('8', 'A'): Actions.SPLIT.name,

            ('9', '2'): Actions.SPLIT.name,
            ('9', '3'): Actions.SPLIT.name,
            ('9', '4'): Actions.SPLIT.name,
            ('9', '5'): Actions.SPLIT.name,
            ('9', '6'): Actions.SPLIT.name,
            ('9', '7'): Actions.STAND.name,
            ('9', '8'): Actions.SPLIT.name,
            ('9', '9'): Actions.SPLIT.name,
            ('9', '10'): Actions.STAND.name,
            ('9', 'J'): Actions.STAND.name,
            ('9', 'Q'): Actions.STAND.name,
            ('9', 'K'): Actions.STAND.name,
            ('9', 'A'): Actions.STAND.name,

            ('10', '2'): Actions.STAND.name,
            ('10', '3'): Actions.STAND.name,
            ('10', '4'): Actions.STAND.name,
            ('10', '5'): Actions.STAND.name,
            ('10', '6'): Actions.STAND.name,
            ('10', '7'): Actions.STAND.name,
            ('10', '8'): Actions.STAND.name,
            ('10', '9'): Actions.STAND.name,
            ('10', '10'): Actions.STAND.name,
            ('10', 'J'): Actions.STAND.name,
            ('10', 'Q'): Actions.STAND.name,
            ('10', 'K'): Actions.STAND.name,
            ('10', 'A'): Actions.STAND.name,

            ('A', '2'): Actions.SPLIT.name,
            ('A', '3'): Actions.SPLIT.name,
            ('A', '4'): Actions.SPLIT.name,
            ('A', '5'): Actions.SPLIT.name,
            ('A', '6'): Actions.SPLIT.name,
            ('A', '7'): Actions.SPLIT.name,
            ('A', '8'): Actions.SPLIT.name,
            ('A', '9'): Actions.SPLIT.name,
            ('A', '10'): Actions.SPLIT.name,
            ('A', 'J'): Actions.SPLIT.name,
            ('A', 'Q'): Actions.SPLIT.name,
            ('A', 'K'): Actions.SPLIT.name,
            ('A', 'A'): Actions.SPLIT.name,

        }
    }
